### ISSUE TITLE
GM_addStyle

### ISSUE THREAD

**Issue by moan0s** [blinry/show-alt-text-userscript#1]
After installation following the readme I only have this error in the console, although `GM_addStyle` seems to be defined

```
Script error in [Greasemonkey script raw.githubusercontent.com/Show Alt Text; version 0.2.0]:
ReferenceError: GM_addStyle is not defined Show Alt Text:107:19
    <anonymous> user-script:raw.githubusercontent.com/Show Alt Text:107
```
I use Firefox 87.0 on arch with greasemonkey freshly installed. Show alt text userscript is the only script running

**Comment by blinry** [comment]
Could reproduce, thanks! Greasemonkey seems to have changed its API, I now recommend [Tampermonkey](https://addons.mozilla.org/de/firefox/addon/tampermonkey/) on Firefox, as well. (Which also has the advantage of a built-in script editor. :)
